apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling
  namespace: stirling
  labels:
    app.kubernetes.io/instance: stirling
    app.kubernetes.io/name: stirling
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
