apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
  namespace: ntfy
  labels:
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/name: ntfy
spec:
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
